Algoritmo "questão 12"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/08/2020

Var

NOME: CARACTER
IDADE: INTEIRO
RESULTADO: INTEIRO


Inicio
ESCREVA ("DIGITE SEU NOME: ")
LEIA (NOME)
ESCREVAL()
ESCREVA ("DIGITE SUA IDADE: ")
LEIA (IDADE)
ESCREVAL ()
         RESULTADO <- (IDADE*365)
   ESCREVA ("VOCÊ JÁ VIVEU", RESULTADO, " DIAS")



fimalgoritmo
