Algoritmo "questão 4"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/08/2020
Var
  A: INTEIRO


Inicio
   ESCREVA ("DIGITE SUA TEMPERATURA:")
   LEIA (A)
   ESCREVAL ()
   SE (A>=25)ENTAO
      ESCREVA("ESTÁ MUITO QUENTE!")
   SENAO
      SE (A<=25)ENTAO
         ESCREVA("ESTÁ AGRADÁVEL!")
      FIMSE
   FIMSE
fimalgoritmo

inicio


fimalgoritmo
